# -*- coding: utf-8 -*-
"""finetuning.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gQJBujp0FLz8Wrv8tgGNwZJfnSZy36Wk

# Installation

### Librairies Installation
"""

!pip install -q transformers==4.46.3 datasets peft accelerate bitsandbytes trl==0.12.1
!pip install -q huggingface_hub

"""### Logging Hugging Face"""

import os

from huggingface_hub import login

hf_token = os.getenv("HF_TOKEN")
if not hf_token:
    raise ValueError("Set the HF_TOKEN environment variable before running this script.")
login(hf_token)

# Cellule 2b : Libérer de l'espace disque (OBLIGATOIRE sur Colab gratuit)
# Colab a ~15–20 GB. Mistral 7B ≈ 14 GB au téléchargement → "No space left on device"
import shutil, os

!df -h /

# Vider le cache pip (1–2 GB)
!pip cache purge

# Vider tout le cache Hugging Face (modèles déjà téléchargés = plusieurs GB)
cache_hub = os.path.expanduser("~/.cache/huggingface/hub")
if os.path.exists(cache_hub):
    shutil.rmtree(cache_hub)
    os.makedirs(cache_hub)
    print("Cache Hugging Face vidé. Mistral 7B sera téléchargé au prochain run.")

!df -h /
print("\n→ Il faut au moins ~12 GB libres pour télécharger Mistral 7B.")

"""### Loading the model - Mistral 7B"""

import torch
from transformers import AutoModelForCausalLM, AutoTokenizer, BitsAndBytesConfig

model_name = "mistralai/Mistral-7B-Instruct-v0.3"

bnb_config = BitsAndBytesConfig(
    load_in_4bit=True,
    bnb_4bit_quant_type="nf4",
    bnb_4bit_compute_dtype=torch.float16,
    bnb_4bit_use_double_quant=True,
)

model = AutoModelForCausalLM.from_pretrained(
    model_name,
    quantization_config=bnb_config,
    device_map="auto",
    attn_implementation="eager",  # Évite les erreurs Flash Attention sur T4
)

tokenizer = AutoTokenizer.from_pretrained(model_name)
tokenizer.pad_token = tokenizer.eos_token
tokenizer.padding_side = "right"

from peft import LoraConfig, prepare_model_for_kbit_training, get_peft_model

model = prepare_model_for_kbit_training(model)

lora_config = LoraConfig(
    r=16,
    lora_alpha=32,
    lora_dropout=0.05,
    bias="none",
    task_type="CAUSAL_LM",
    target_modules=["q_proj", "k_proj", "v_proj", "o_proj",
                     "gate_proj", "up_proj", "down_proj"],
)

model = get_peft_model(model, lora_config)
model.print_trainable_parameters()

from google.colab import files

uploaded = files.upload()  # Selectionne data.jsonl depuis ton ordi

import json, re

def chatml_to_mistral(text):
    system = re.search(r'<\|im_start\|>system\n(.*?)<\|im_end\|>', text, re.DOTALL)
    user = re.search(r'<\|im_start\|>user\n(.*?)<\|im_end\|>', text, re.DOTALL)
    assistant = re.search(r'<\|im_start\|>assistant\n(.*?)<\|im_end\|>', text, re.DOTALL)

    system_text = system.group(1).strip() if system else ""
    user_text = user.group(1).strip() if user else ""
    assistant_text = assistant.group(1).strip() if assistant else ""

    inst_content = f"{system_text}\n\n{user_text}" if system_text else user_text
    return f"<s>[INST] {inst_content} [/INST]{assistant_text}</s>"

converted = []
with open("data_x_en.jsonl", "r") as f:
    for line in f:
        example = json.loads(line)
        example["text"] = chatml_to_mistral(example["text"])
        converted.append(example)

with open("data_mistral.jsonl", "w") as f:
    for ex in converted:
        f.write(json.dumps(ex) + "\n")

print(f"Convertis : {len(converted)} exemples")
print(f"\nAperçu du premier exemple :\n{converted[0]['text'][:400]}")

from datasets import load_dataset

dataset = load_dataset("json", data_files="data_mistral.jsonl", split="train")
print(f"Dataset : {len(dataset)} exemples")
print(dataset[0]["text"][:400])

"""# Training


"""

# Cellule 6
from trl import SFTTrainer
from transformers import TrainingArguments

training_args = TrainingArguments(
    output_dir="./results",
    num_train_epochs=2,
    per_device_train_batch_size=1,
    gradient_accumulation_steps=8,
    learning_rate=2e-4,
    fp16=True,
    logging_steps=10,
    save_strategy="epoch",
    optim="paged_adamw_8bit",
    warmup_ratio=0.03,
    lr_scheduler_type="cosine",
    report_to="none",
)

trainer = SFTTrainer(
    model=model,
    train_dataset=dataset,
    args=training_args,
    tokenizer=tokenizer,
    dataset_text_field="text",
    max_seq_length=512,
    packing=True,
)

trainer.train()

from transformers import pipeline

pipe = pipeline("text-generation", model=model, tokenizer=tokenizer)

prompt = "<s>[INST] You are an expert at writing viral Twitter/X threads. You turn any topic into a captivating thread of 5 to 15 tweets. Each thread starts with an irresistible hook, uses storytelling, striking numbers, punchy analogies, and ends with a CTA (call to action). You write in English. You use emojis sparingly. Each tweet is 280 characters max.\n\nWrite a viral thread about the psychology of pricing. [/INST]"

result = pipe(prompt, max_new_tokens=300, do_sample=True, temperature=0.7)
print(result[0]["generated_text"][len(prompt):])

test_topics = [
    "Write a viral thread about why most people fail at habits.",
    "Write a thread about the hidden cost of multitasking.",
    "Write a thread about how Airbnb almost died.",
]

for topic in test_topics:
    prompt = f"<s>[INST] You are an expert at writing viral Twitter/X threads. You turn any topic into a captivating thread of 5 to 15 tweets. Each thread starts with an irresistible hook, uses storytelling, striking numbers, punchy analogies, and ends with a CTA (call to action). You write in English. You use emojis sparingly. Each tweet is 280 characters max.\n\n{topic} [/INST]"
    result = pipe(prompt, max_new_tokens=300, do_sample=True, temperature=0.7)
    print(f"\n{'='*60}")
    print(f"SUJET : {topic}")
    print(f"{'='*60}")
    print(result[0]["generated_text"][len(prompt):])

# Cellule 8 : Sauvegarder les adaptateurs LoRA
model.save_pretrained("./mistral-threads-lora")
tokenizer.save_pretrained("./mistral-threads-lora")

# Push sur HF Hub
model.push_to_hub("nyri/mistral-7b-threads-finetuned")
tokenizer.push_to_hub("nyri/mistral-7b-threads-finetuned")

from peft import AutoPeftModelForCausalLM

merged_model = AutoPeftModelForCausalLM.from_pretrained(
    "./mistral-threads-lora",
    torch_dtype=torch.float16,
    device_map="auto",
)
merged_model = merged_model.merge_and_unload()
merged_model.save_pretrained("./mistral-threads-merged")
merged_model.push_to_hub("nyri/mistral-7b-threads-finetuned-merged")
